#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us
  search_drivers: true
  identity:
    realname: 'LR'
    username: lr3884
    password: '$6$fnhHU/DbUCACbDMx$EahMMuoSecKN7Z47VEhCo92XDYr619F5vzsslNka7ebBNygDNc2iERvXEmUOFlMwA1K.rcXlHvdkZYUOCpyvN0'
    hostname: ubuntu
  ssh:
    install-server: true
    allow-pw: true
    authorized-keys: []
  codecs:
    install: true
  drivers:
    install: true
  timezone: Asia/Singapore
  updates: all
  shutdown: reboot
  late-commands:
    - curtin in-target -- sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/lucasrainett/autoinstall/master/script.sh)"