name = "Moonlight"
description = "Streams games from a host PC to this machine"
website = "https://moonlight-stream.org/"

[linux]
installMethod = "flatpak"

[macos]
installMethod = "homebrew"

[windows]
installMethod = "winget"
