name = "Podman Desktop"
description = "Desktop app for managing containers, pods, images and Kubernetes clusters"
website = "https://podman-desktop.io"

capabilities = ["container-gui", "containers"]

[linux]
installMethod = "flatpak"

[macos]
installMethod = "homebrew"

[windows]
installMethod = "winget"
